import Head from "next/head";
import styles from "../styles/Home.module.css";
import WeatherBoard from "../components/WeatherBoard";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tivix Weather Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WeatherBoard />
    </div>
  );
}
